### ISSUE TITLE
[FEAT] - add CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by lubnafathima** [Evavic44/portfolio-ideas#108]
**Is your feature request related to a problem? Please describe.**
Hey
Since this repository have so many contributes it would be helpful to have a **CODE_OF_CONDUCT.md** file

**Describe the solution you'd like**
[refer here](https://opensource.guide/code-of-conduct/)

**Describe alternatives you've considered**
If your interested please assign it to me

**Comment by lubnafathima** [comment]
I would like to contribute to this issue.

**Comment by Evavic44** [comment]
> I would like to contribute to this issue.

Assigned. Go ahead. 👍🏽
