### ISSUE TITLE
Update my twitter profile link

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/portfolio-ideas#169]
I changed my Twitter username recently but the link to my Twitter profile is still pointing to the old URL

## Fix
Replace the old URL with https://twitter.com/victorekea

## Issue Source
This issue can be found in the **Need More Help** section inside the `Contributing.md` file.
Link: [Need More Help](https://github.com/Evavic44/portfolio-ideas/blob/main/CONTRIBUTING.md#need-more-help-)

**Comment by hxpdong** [comment]
Please assign me

**Comment by hxpdong** [comment]
Sorry, I already fixed the link for you but I don't know what to do next step. I have just done something and it has unsigned me off. Sorry for wasting your time so much! :(

**Comment by Evavic44** [comment]
> Sorry, I already fixed the link for you but I don't know what to do next step. I have just done something and it has unsigned me off. Sorry for wasting your time so much! :(

Oh, it's no waste at all. 
If you've fixed the issue, the next step is raising a pull request from your forked repository. 
You can refer to this [guide](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request#creating-a-pull-request) for more info, thanks. 😎
