### ISSUE TITLE
[FEAT] - Automate site deployment using Github Actions

### ISSUE THREAD

**Issue by vimode** [Evavic44/portfolio-ideas#220]
**Is your feature request related to a problem? Please describe.**
The current contributing guidelines recommends contributor(s) to update the README.md using the Github's web interface. 
But for the updates to reflect in deployed version on the  [portfolio](https://portfolio-ideas.vercel.app/portfolio.html) page, the `npm run deploy` command needs to be run locally.  

**Describe the solution you'd like**
Github Actions could be used to run the deploy command once the changes are accepted and the PR is merged.

**Describe alternatives you've considered**
Other alternative is to update the Contributing guidelines to ask the contributor to run the deploy command and then make a PR. This does make the contributing process a little convoluted and confusing.

**Additional context**
This feature request discussion started in #218 

Thank you.

**Comment by Evavic44** [comment]
Thanks for raising the issue, @vimode. I'll look into it.

**Comment by vimode** [comment]
The workflow needs to first run the deploy command and then push those changes back to the repo. 

The [Node.js starter workflow](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs) should help with that, That should cover the first half of the workflow.

The second part I am not sure about, how to setup a github-actions bot(?) to push those changes (copied filed) back to the repo. Can we generate and use a github token (safely) in the workflow to authenticate that push from `{{ github.actor }}` (i.e. you)? 

I could help setting it up if you could guide me to how to do the second half of the workflow.

Thank you

**Comment by Evavic44** [comment]
I was thinking we use the [Prettier GitHub action](https://github.com/creyD/prettier_action). To keep things very simple.

**Comment by vimode** [comment]
Just for the write permission after running the deploy command? or for the complete workflow? 
If its just for the write permission, it seems to be using [action/checkout](https://github.com/actions/checkout) for the token. So we could use that directly instead for the auth part to push the deployment changes? 

Sorry, I am new to using github workflows, so the many question.

**Comment by Evavic44** [comment]
Same here. Hence the reason I proposed a simple solution. It's for the complete workflow, though it'll require a PAT from my end, otherwise, there's nothing much to do except create the workflow YML file and connect it using my token. 

What do you think?

**Comment by vimode** [comment]
I don't think you need to generate a new PAT.
If I am understanding [this correctly](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), a unique `GITHUB_TOKEN` is auto generated for each workflow run. And it seems to have most of the write permissions we need. 
 
I think it would be better idea to create a new test branch to test this workflow in that branch before merging.

**Comment by Evavic44** [comment]
Yeah, you're right. I'm assigning this to you. When you're free, see if you can test it on another branch.

**Comment by Evavic44** [comment]
@all-contributors please add @vimode for code and doc
