### ISSUE TITLE
GitHub URL not available for Rick Waalders portfolio

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/portfolio-ideas#29]
## Issue
The GitHub URL for Rick Waalders portfolio is pointing to his portfolio website because the GitHub URL is not available.

## Recommended Fix
Remove the link and replace it with `None`

```diff
- [GitHub](https://rickwaalders.com)
+ None 
```

**Comment by lubnafathima** [comment]
hey @Evavic44 
what's the issue here?
It was supposed to point to his portfolio website right?
Why you want to replace it to 'none'?

**Comment by Evavic44** [comment]
> hey @Evavic44 what's the issue here? It was supposed to point to his portfolio website right? Why you want to replace it to 'none'?

The GitHub URL should point to the GitHub but it's pointing to the Live URL, and that is incorrect. So change it to `none`.
