### ISSUE TITLE
Issue in readme

### ISSUE THREAD

**Issue by shivaylamba** [Evavic44/portfolio-ideas#345]
For [brittanychiang.com](https://brittanychiang.com/) portfolio the image is incorrect. And this particular version of the portfolio is not open sourced. 

The actual URL for the image shown in the table is [brittanychiang.com v4](https://v4.brittanychiang.com)

**Comment by Evavic44** [comment]
Thanks for spotting this. Feel free to update the GitHub and Live URL.
GitHub: https://github.com/bchiang7/v4
Live URL: https://v4.brittanychiang.com/
