### ISSUE TITLE
[Bug] - Remove inactive portfolio 

### ISSUE THREAD

**Issue by PriyansuMaurya** [Evavic44/portfolio-ideas#346]
**Is there a problem related to your feature request? Please explain.**
The portfolio is no longer active, and the image is missing.

[mhbaando.com](https://mhbaando.com/)

**What solution would you prefer?**
I suggest removing it.

**Have you considered any other options?**
We could inform the author that it's not live.

**Is there any additional context or screenshots you can provide for the feature request?**
![image](https://github.com/Evavic44/portfolio-ideas/assets/101447544/90522c92-31e9-4359-ad87-c0fbe769619b)

**Comment by Evavic44** [comment]
Thanks for raising this issue, @PriyansuMaurya You can go ahead and remove it.
