### ISSUE TITLE
Portfolio Suggestion 

### ISSUE THREAD

**Issue by B2-krunalrana** [Evavic44/portfolio-ideas#356]
New Portfolio Suggestion 

Here is hosted link : https://codewithsadee.github.io/vcard-personal-portfolio/?fullname=Krunal+Rana&email=ranakrunal2704%40gmail.com&message=dd#

git hub link : https://github.com/codewithsadee/vcard-personal-portfolio

Screen Shots : 
![image](https://github.com/Evavic44/portfolio-ideas/assets/90046525/4073d985-e7c4-4ad2-af38-364afff20dec)

Feature : 
very light weight and quick load  with amazing Ui

**Comment by israelmitolu** [comment]
Hi @B2-krunalrana thanks for adding this
For next time's sake, you can use an [open issue](https://github.com/Evavic44/portfolio-ideas/issues/104) we've created that is dedicated to suggesting portfolios
