### ISSUE TITLE
Adding my portfolio

### ISSUE THREAD

**Issue by affancoder** [Evavic44/portfolio-ideas#413]
Full Name - MD Affan Asghar

live link - https://affancoder.github.io/Portfolio_Website/

github source - https://github.com/affancoder/Portfolio_Website

Thumbnail - ![hireweb](https://github.com/Evavic44/portfolio-ideas/assets/113276865/dda1229e-4996-43c8-9116-227c8920c2f2)

**Comment by israelmitolu** [comment]
Hi @affancoder 
We have created an issue dedicated for you to add your portfolio details, instead of creating a new issue. 
I would go ahead to add this to the repo, but in case you want us to add next time, kindly add the details in #104
