### ISSUE TITLE
[FEAT] - Feature Info

### ISSUE THREAD

**Issue by affancoder** [Evavic44/portfolio-ideas#422]
Full Name - **MD Affan Asghar**

live link - https://affancoder.github.io/Portfolio_Website/

Github source - https://github.com/affancoder/Portfolio_Website

![320790194-dda1229e-4996-43c8-9116-227c8920c2f2](https://github.com/Evavic44/portfolio-ideas/assets/113276865/93233b6e-5cf3-499d-81fd-191ce301c027)

technology used - HTML, CSS & JavaScript

**Comment by israelmitolu** [comment]
@affancoder your portfolio has been added already

**Comment by affancoder** [comment]
Thanks a lot for adding my portfolio to your portfolio-ideas

I will add this contribution to my cv.
