### ISSUE TITLE
[FEAT] - Feature Info

### ISSUE THREAD

**Issue by shiv1819** [Evavic44/portfolio-ideas#465]
Hello guys, thats my portfolio, can you add in the list? Thanks!!
URL : [shivampanchal.vercel.app
![Screenshot 2024-07-28 171235](https://github.com/user-attachments/assets/1f740ae5-1299-451c-9e8a-3c034c7a995c)
]( http://shivampanchal.vercel.app )

**Comment by Evavic44** [comment]
Requesting for portfolios to be added by the community should be done in #104. Kindly respond with the appropriate parameters in that issue. Thanks.
