### ISSUE TITLE
Dipesh Murmu

### ISSUE THREAD

**Issue by dipeshmurmu2005** [Evavic44/portfolio-ideas#479]
Dipesh Murmu
website link - https://dipeshmurmu.com.np
Tailwind, Alpine, Laravel, Livewire

Now Please Remove the portfolio that i have added earlier the website link was https://portfolio.itsmedipesh.xyz  or replace it with the data given above

_Originally posted by @dipeshmurmu2005 in https://github.com/Evavic44/portfolio-ideas/issues/104#issuecomment-2294814658_

**Comment by Evavic44** [comment]
Changes already suggested in #104. Closing this as duplicate
