### ISSUE TITLE
Added my portfolio

### ISSUE THREAD

**Issue by Emeka212** [Evavic44/portfolio-ideas#67]
i just added my portfolio, await a response from you, this will be my first GitHub contribution, Lol but kinda cool

**Comment by Evavic44** [comment]
Hey, @Emeka212 I haven't seen your pull request. Can you kindly raise one so I can merge it? If you need any help doing that, you can follow this [Contributing Guidelines](https://github.com/Evavic44/portfolio-ideas/blob/main/CONTRIBUTING.md)

**Comment by Emeka212** [comment]
@Evavic44 hmm, I am kinda finding it hard to make a pull request, I might need help with that, the link you provided ain't helping much. I thought the process is like this.

fork the repo
make some changes
commit that changes
push back to my own fork repo

// not this is were i am lost, don't know what next

**Comment by Evavic44** [comment]
Yes, you're on the right path. The missing step is raising a pull request. After pushing back to your fork, you need to raise a pull request to this main repository. 

Check this repo and you should find this button if you pushed it correctly. 

<img src="https://user-images.githubusercontent.com/62628408/174435166-fa51fc8a-a08f-4c2f-9b37-397c5d81ec05.png" width="500px">

You can check out this doc for more info.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
